# Generated by Django 3.2.7 on 2021-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('sender', models.CharField(max_length=300)),
                ('reply_to', models.CharField(max_length=300, null=True)),
                ('recipient', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(max_length=300)),
                ('cc', models.CharField(max_length=300, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
