# Generated by Django 3.2.10 on 2022-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='cc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='recipient',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='reply_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
