# Generated by Django 3.2.10 on 2022-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20220226_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='enabled',
            field=models.BooleanField(default=True, null=False),
        ),
    ]
