# Generated by Django 3.2.10 on 2022-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_add_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='enabled',
            field=models.BooleanField(blank=True),
        ),
    ]
