# Generated by Django 3.2.7 on 2021-12-05 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGameRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('player_answer', models.BooleanField(null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emails')),
            ],
        ),
        migrations.CreateModel(
            name='GameRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('emails', models.ManyToManyField(related_name='emails_in_gamerun', through='gameruns.EmailGameRuns', to='emails.Emails')),
            ],
        ),
        migrations.AddField(
            model_name='emailgameruns',
            name='game_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameruns.gameruns'),
        ),
    ]
