# Generated by Django 3.2.10 on 2022-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameruns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameruns',
            name='player_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameruns',
            name='player_gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
