# Generated by Django 3.2.10 on 2022-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
