# Generated by Django 3.2.10 on 2022-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_added_type_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
